### PR TITLE
Added New similarity algorithm using Gensim Library 

### PR DESCRIPTION
**Pull request by raszidzie**
Gensim is billed as a Natural Language Processing package that does ‘Topic Modeling for Humans’. But it is practically much more than that. It is a leading and a state-of-the-art package for processing texts, working with word vector models (such as Word2Vec, FastText etc) and for building topic models.

-Updated READ.me
-Updated requirements.txt
- Uploaded new file "gensim_similarity"

### CODE REVIEW

**Comment by luozhouyang** [comment]
Good idea! But could you please organize your code to a class, something like **GensimSimilarity**?

**Comment by raszidzie** [comment]
> Good idea! But could you please organize your code to a class, something like **GensimSimilarity**?
I updated the file you can check now :)

**Comment by luozhouyang** [comment]
Here are the exceptions:
exception

**Comment by raszidzie** [comment]
workdir folder should locate same directory with program file.

**Comment by luozhouyang** [comment]
It seems that integration with **gensim** is not that easy.  

Both **gensim** and **nltk** are heavy libraries, and are often used in deep learning based NLP tasks. 

I tend to keep this library simple and small. Let it complement these frameworks, not integrate with them.

**Pull request merged**
